# Generated by Django 4.2.4 on 2024-04-09 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Black Comedy', 'Black Comedy'), ('Conditional Joke', 'Conditional Joke'), ('Dad Joke', 'Dad Joke'), ('Knock-knock', 'Knock-knock'), ('Mathematical Joke', 'Mathematical Joke')], max_length=20)),
                ('like', models.IntegerField()),
                ('share', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
