# Generated by Django 4.2.4 on 2024-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Black Comedy', 'Black Comedy'), ('Conditional Joke', 'Conditional Joke'), ('Dad Joke', 'Dad Joke'), ('Knock-knock', 'Knock-knock'), ('Mathematical Joke', 'Mathematical Joke'), ('Funny Joke', 'Funny Joke')], max_length=20),
        ),
    ]
